# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 中青自动阅读

on:
  workflow_dispatch:
  schedule:
     - cron: '6 1-12/2 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
     READ_BODY1: ${{ secrets.READ_BODY1 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看点自动阅读】'
        if: env.READ_BODY1
        run: |
          node quanx/youth_read.py
        env:
          READ_BODY1: ${{ secrets.READ_BODY1 }}
